"""
Django settings for egstutorting project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

import sys
print(f"SETTINGS LOADED from: {__name__} | file: {__file__}", file=sys.stderr)

import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import logging.config

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'playground': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-build-key-only-for-collectstatic')

# Warn if using default key in production
if SECRET_KEY == 'django-insecure-build-key-only-for-collectstatic' and not os.getenv('RAILWAY_ENVIRONMENT_NAME'):
    import warnings
    warnings.warn("Using default SECRET_KEY - set SECRET_KEY environment variable for production!")

# Environment variables for sensitive data
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_BROKER_URL')  # Use same Redis for results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Memory management for Celery workers
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks to prevent memory leaks
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 100000  # Restart worker at 100MB memory usage
CELERY_TASK_ACKS_LATE = True  # Don't ack tasks until they complete successfully
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch 1 task at a time to reduce memory
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject tasks if worker dies

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URL = os.getenv('GOOGLE_REDIRECT_URL', "https://egstutoring-portal.ca/api/google/oauth2callback")
FERNET_SECRET = os.getenv('FERNET_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Auto-detect Railway domain or use environment variable
if os.getenv('RAILWAY_ENVIRONMENT_NAME'):
    # Running on Railway - allow Railway domains
    ALLOWED_HOSTS = [
        os.getenv('RAILWAY_PUBLIC_DOMAIN', ''),
        '*.railway.app',
        'egstutoring-portal.ca',
        'www.egstutoring-portal.ca',
        'localhost',
        '127.0.0.1'
    ]
else:
    # Local development or custom deployment
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rest_passwordreset',
    'playground',
    'rest_framework',
    'corsheaders',
    'django_cryptography',
    'anymail',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174", 
    "http://localhost:5175",
    "http://localhost:5176",
    "http://localhost:5177",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5176", 
    "http://127.0.0.1:5177",
    "https://egstutoring-portal.ca",
    "https://www.egstutoring-portal.ca",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://localhost:5176",
    "http://localhost:5177",
    "http://localhost:8000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5176",
    "http://127.0.0.1:5177",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'egstutorting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

WSGI_APPLICATION = 'egstutorting.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use PostgreSQL for Supabase connection
import dj_database_url

# If DATABASE_URL is provided, use it (preferred method for Supabase)
database_url = os.getenv('DATABASE_URL', '').strip()
print(f"DEBUG: DATABASE_URL exists: {bool(database_url)}", file=sys.stderr)
print(f"DEBUG: DATABASE_URL first 30 chars: '{database_url[:30]}'", file=sys.stderr)
print(f"DEBUG: DATABASE_URL starts with postgres: {database_url.startswith(('postgresql://', 'postgres://')) if database_url else False}", file=sys.stderr)
if database_url and database_url.startswith(('postgresql://', 'postgres://')):
    # Add SSL if not already present
    if '?sslmode=' not in database_url:
        database_url += '?sslmode=require'
    
    DATABASES = {
        'default': dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Ensure SSL options are set
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    DATABASES['default']['OPTIONS'].update({
        'sslmode': 'require',
    })
    print(f"DATABASE: Using PostgreSQL - {DATABASES['default']['HOST']}", file=sys.stderr)
# Otherwise use individual parameters
elif all([os.getenv('DB_NAME'), os.getenv('DB_USER'), os.getenv('DB_PASSWORD'), os.getenv('DB_HOST')]):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
    print(f"DATABASE: Using PostgreSQL - {os.getenv('DB_HOST')}", file=sys.stderr)
# Fallback to SQLite for development if PostgreSQL not configured
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    print(f"DATABASE: Using SQLite - {BASE_DIR / 'db.sqlite3'}", file=sys.stderr)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'playground.user'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configure static files directories for development
if not os.getenv('RAILWAY_ENVIRONMENT'):
    STATICFILES_DIRS = [
        BASE_DIR / "media",  # Include media directory in static files for dev
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Environment-based configuration
import os

# URL Configuration
BACKEND_URL = os.getenv("BACKEND_URL", "https://egstutoring-portal.ca")
FRONTEND_URL = os.getenv("FRONTEND_URL", "https://egstutoring-portal.ca")

# Email Configuration
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@egstutoring-portal.ca")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "info@egstutoring.ca")

# Mailgun API Configuration
MAILGUN_API_KEY = os.getenv("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = os.getenv("MAILGUN_DOMAIN", "mail.egstutoring-portal.ca")
MAILGUN_API_URL = f"https://api.mailgun.net/v3/{MAILGUN_DOMAIN}/messages"

# Use console backend for development, custom Mailgun for production
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", 'django.core.mail.backends.console.EmailBackend')

#--------------------------------------------

CORS_ALLOWS_CREDENTIALS = True

# Railway Persistent Storage Configuration
# Railway provides persistent storage mounted at /data
if os.getenv('RAILWAY_ENVIRONMENT'):
    # Use Railway's persistent storage
    MEDIA_ROOT = '/data/media'
    MEDIA_URL = '/media/'
else:
    # Local development
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration for serving media files
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Tell WhiteNoise to serve media files
WHITENOISE_ROOT_SQUASH = 3600  # Cache media files for 1 hour

# Django REST Password Reset configuration
DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE = True

# Stripe configuration - use environment variables
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY') 
STRIPE_WEBHOOK_KEY = os.getenv('STRIPE_WEBHOOK_KEY', '')

