# Generated by Django 5.1.4 on 2025-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringrequest',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
