# Generated by Django 5.2 on 2025-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_tutoringrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
