# Generated by Django 5.2 on 2025-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
