# Generated by Django 5.2 on 2025-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_tutoringrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorresponse',
            name='tutor',
            field=models.CharField(max_length=50),
        ),
    ]
