# Generated by Django 5.1.4 on 2025-02-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringrequest',
            name='parent',
            field=models.CharField(max_length=50),
        ),
    ]
