# Generated by Django 5.2 on 2025-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_user_first_name_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
