# Generated by Django 5.1.4 on 2025-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_tutoringrequest_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.CharField(default='parent', max_length=100),
        ),
    ]
