# Generated by Django 5.1.3 on 2025-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
