# Generated by Django 5.2.1 on 2025-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_airequest_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tutor', models.CharField(max_length=50)),
                ('email', models.CharField(default='None', max_length=70)),
                ('OnlineHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('InPersonHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TotalBeforeTax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
