# Generated by Django 5.1.4 on 2025-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_user_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
