# Generated by Django 5.1.3 on 2025-07-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Announcements',
        ),
    ]
