# Generated by Django 5.2.1 on 2025-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_hours_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedtutor',
            name='status',
            field=models.CharField(choices=[('Accepted', 'ACCEPTED'), ('Disputed', 'DISPUTED'), ('Resolved', 'RESOLVED'), ('Void', 'VOID')], default='ACCEPTED', max_length=20),
        ),
    ]
