# Generated by Django 5.2 on 2025-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyhours',
            name='email',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
