# Generated by Django 5.1.3 on 2025-07-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_user_google_access_token_user_google_refresh_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_access_token',
            new_name='_encrypted_google_access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='google_refresh_token',
            new_name='_encrypted_google_refresh_token',
        ),
    ]
