# Generated by Django 5.1.3 on 2025-07-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_rename_google_access_token_user__encrypted_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
