# Generated by Django 5.1.3 on 2025-07-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_user_google_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='city',
            field=models.CharField(choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Barrie', 'Barrie'), ('Belleville', 'Belleville'), ('Brampton', 'Brampton'), ('Brantford', 'Brantford'), ('Burlington', 'Burlington'), ('Cambridge', 'Cambridge'), ('Chatham-Kent', 'Chatham-Kent'), ('Clarington', 'Clarington'), ('Collingwood', 'Collingwood'), ('Cornwall', 'Cornwall'), ('Dryden', 'Dryden'), ('Georgina', 'Georgina'), ('Grimsby', 'Grimsby'), ('Guelph', 'Guelph'), ('Hamilton', 'Hamilton'), ('Huntsville', 'Huntsville'), ('Innisfil', 'Innisfil'), ('Kawartha Lakes', 'Kawartha Lakes'), ('Kenora', 'Kenora'), ('Kingston', 'Kingston'), ('Kitchener', 'Kitchener'), ('Leamington', 'Leamington'), ('London', 'London'), ('Markham', 'Markham'), ('Midland', 'Midland'), ('Milton', 'Milton'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('Niagara Falls', 'Niagara Falls'), ('Niagara-on-the-Lake', 'Niagara-on-the-Lake'), ('North Bay', 'North Bay'), ('Oakville', 'Oakville'), ('Orangeville', 'Orangeville'), ('Orillia', 'Orillia'), ('Oshawa', 'Oshawa'), ('Ottawa', 'Ottawa'), ('Peterborough', 'Peterborough'), ('Pickering', 'Pickering'), ('Quinte West', 'Quinte West'), ('Richmond Hill', 'Richmond Hill'), ('Sarnia', 'Sarnia'), ('St. Catharines', 'St. Catharines'), ('St. Thomas', 'St. Thomas'), ('Stratford', 'Stratford'), ('Sudbury', 'Sudbury'), ('Tecumseh', 'Tecumseh'), ('Thunder Bay', 'Thunder Bay'), ('Timmins', 'Timmins'), ('Toronto', 'Toronto'), ('Vaughan', 'Vaughan'), ('Wasaga Beach', 'Wasaga Beach'), ('Waterloo', 'Waterloo'), ('Welland', 'Welland'), ('Whitby', 'Whitby'), ('Windsor', 'Windsor'), ('Woodstock', 'Woodstock')], default='Toronto', max_length=30),
        ),
    ]
