# Generated by Django 5.2 on 2025-04-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='is_accepted',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted'), ('Renew', 'Renew')], default='Not Accepted', max_length=15),
        ),
        migrations.AlterField(
            model_name='acceptedtutor',
            name='tutor',
            field=models.CharField(max_length=50),
        ),
    ]
