# Generated by Django 5.2 on 2025-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_tutorresponse_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorresponse',
            name='request',
            field=models.CharField(max_length=50),
        ),
    ]
