# Generated by Django 5.1.3 on 2025-07-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_user_files_userdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='files',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
