# Generated by Django 5.1.3 on 2025-07-25 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_alter_user_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='user_error/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_tickets_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
