# Generated by Django 5.1.3 on 2025-07-26 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_errorticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyhours',
            name='date',
        ),
        migrations.AddField(
            model_name='hours',
            name='eligible',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Late', 'LATE')], default='Eligible', max_length=15),
        ),
        migrations.AddField(
            model_name='monthlyhours',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlyhours',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='monthly_reports/')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_report_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_report_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='cad', max_length=5)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_hours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_record', to='playground.monthlyhours')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('monthly_hours', 'stripe_transfer_id')},
            },
        ),
    ]
