# Generated by Django 5.1.3 on 2025-07-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_remove_monthlyhours_date_hours_eligible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyhours',
            name='email',
        ),
        migrations.RemoveField(
            model_name='weeklyhours',
            name='email',
        ),
    ]
