# Generated by Django 5.1.3 on 2025-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_alter_user_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_picture/default-profile-picture.jpeg', upload_to='profile_picture/'),
        ),
    ]
