# Generated by Django 5.1.3 on 2025-08-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-year', '-month', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('tutor', 'student', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='additional_comments',
            field=models.TextField(blank=True, default='', help_text='Any additional comments or observations'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='areas_for_improvement',
            field=models.TextField(default='', help_text='Areas where the student needs to improve'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='goals_for_next_month',
            field=models.TextField(default='', help_text='Goals and objectives for the upcoming month'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='homework_completion',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', help_text='How well the student completes homework assignments', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='participation_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text="Student's level of participation during sessions", max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='progress_summary',
            field=models.TextField(default='', help_text="Overall summary of the student's progress this month"),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='strengths',
            field=models.TextField(default='', help_text="Student's strengths observed during tutoring sessions"),
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='file',
        ),
    ]
