# Generated by Django 5.1.3 on 2025-08-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_alter_monthlyreport_options_and_more'),
    ]

    operations = [
        # Remove Django's built-in first_name and last_name fields
        # Keep the custom firstName and lastName fields
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
