# Generated by Django 5.1.3 on 2025-08-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_auto_20250820_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Description of the dispute')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text='Admin response to dispute', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='playground.hours')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hour', 'complainer')},
            },
        ),
    ]
