# Generated by Django 5.1.3 on 2025-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_user_phone_tutorcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='eligible',
            field=models.CharField(choices=[('Submitted', 'SUBMITTED'), ('Late', 'LATE'), ('Eligible', 'ELIGIBLE')], default='Eligible', max_length=15),
        ),
    ]
