# Generated by Django 5.1.3 on 2025-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_alter_hours_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='edit_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hours',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='tutor_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
