# Generated by Django 5.1.3 on 2025-08-28 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_add_edit_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject for which tutor change is requested', max_length=100)),
                ('reason', models.CharField(choices=[('scheduling', 'Scheduling conflicts'), ('teaching_style', 'Teaching style mismatch'), ('communication', 'Communication issues'), ('progress', 'Lack of progress'), ('availability', 'Tutor availability issues'), ('other', 'Other reason')], default='other', max_length=20)),
                ('message', models.TextField(help_text='Detailed reason for requesting tutor change')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text='Admin response to request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('current_tutor', models.ForeignKey(limit_choices_to={'roles': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests_from', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'roles': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_change_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'roles': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_changes_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'student', 'current_tutor', 'subject', 'status')},
            },
        ),
    ]
