# Generated by Django 5.1.3 on 2025-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0026_tutorchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=65.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
