# Generated by Django 5.1.3 on 2025-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0027_referral_credit_amount_referral_used_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='invoice_id',
            field=models.CharField(blank=True, help_text='Stripe invoice ID if invoiced', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='hours',
            name='eligible',
            field=models.CharField(choices=[('Late', 'LATE'), ('Eligible', 'ELIGIBLE')], default='Eligible', max_length=15),
        ),
    ]
