# Generated by Django 5.1.3 on 2025-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0028_add_invoice_status_to_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyhours',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyhours',
            name='transfer_id',
            field=models.CharField(blank=True, help_text='Stripe transfer ID if paid', max_length=100, null=True),
        ),
    ]
