# Generated by Django 5.1.3 on 2025-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0029_add_payout_status_to_monthlyhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
