# Generated by Django 5.1.3 on 2025-09-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0030_add_chat_rate_limiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='audience',
            field=models.CharField(default='all', help_text='Comma-separated roles: e.g., "parent,student" or "all"', max_length=100),
        ),
    ]
