# Generated by Django 5.1.3 on 2025-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0031_update_announcement_audience_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date when report is due (1st of following month)', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', help_text='Report status', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Date when report was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='areas_for_improvement',
            field=models.TextField(blank=True, default='', help_text='Areas where the student needs to improve'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='goals_for_next_month',
            field=models.TextField(blank=True, default='', help_text='Goals and objectives for the upcoming month'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='homework_completion',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', help_text='How well the student completes homework assignments', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='participation_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text="Student's level of participation during sessions", max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='progress_summary',
            field=models.TextField(blank=True, default='', help_text="Overall summary of the student's progress this month"),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='strengths',
            field=models.TextField(blank=True, default='', help_text="Student's strengths observed during tutoring sessions"),
        ),
    ]
