# Generated by Django 5.1.3 on 2025-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0032_monthlyreport_due_date_monthlyreport_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='additional_comments',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='goals_for_next_month',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='homework_completion',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='participation_level',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='progress_summary',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='challenges',
            field=models.TextField(blank=True, default='', help_text='What areas still need extra support or practice?'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='confidence_attitude',
            field=models.TextField(blank=True, default='', help_text="Do you notice any changes in the child's confidence or attitude toward learning?"),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='homework_practice',
            field=models.TextField(blank=True, default='', help_text='How consistent has the child been with completing assignments or practicing skills outside of tutoring?'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='looking_ahead',
            field=models.TextField(blank=True, default='', help_text='What will be the main focus for the next month?'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='overall_progress',
            field=models.TextField(blank=True, default='', help_text="How would you describe the child's progress this month?"),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='parent_support',
            field=models.TextField(blank=True, default='', help_text='Is there anything parents can do at home to reinforce learning?'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='work_habits',
            field=models.TextField(blank=True, default='', help_text="How is the child's focus, participation, and effort during tutoring sessions?"),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='strengths',
            field=models.TextField(blank=True, default='', help_text='What subject areas or skills has the child improved in or shown strong ability?'),
        ),
    ]
