# Generated by Django 5.1.3 on 2025-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_add_tutor_referral_request_model'),
        ('playground', '0033_remove_monthlyreport_additional_comments_and_more'),
    ]

    operations = [
    ]
