# Generated by Django 5.1.3 on 2025-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0034_merge_20251008_0758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorReferralRequest',
        ),
    ]
