# Generated by Django 5.1.3 on 2025-10-10 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0035_remove_tutor_referral_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('referral_code_used', models.CharField(help_text='The tutor code that was used', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('token', models.CharField(help_text='Unique token for referral link', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(limit_choices_to={'roles': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_as_parent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'roles': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'roles': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests_received', to=settings.AUTH_USER_MODEL)),
                ('tutoring_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_request', to='playground.tutoringrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
