# Generated by Django 5.1.3 on 2025-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0036_tutorreferralrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_tour',
            field=models.BooleanField(default=False, help_text='Whether user has completed the onboarding tour'),
        ),
    ]
