# Generated by Django 5.1.3 on 2025-10-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0037_user_has_seen_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Popup title', max_length=255)),
                ('content', models.TextField(help_text='Popup content/message')),
                ('image', models.ImageField(blank=True, help_text='Optional popup image', null=True, upload_to='popups/')),
                ('link', models.URLField(blank=True, help_text='Optional link/call-to-action URL')),
                ('link_text', models.CharField(blank=True, help_text='Text for the link button', max_length=100)),
                ('audience', models.CharField(default='all', help_text='Comma-separated roles: e.g., "parent,student" or "all"', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether popup is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopupDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='playground.popup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'unique_together': {('popup', 'user')},
            },
        ),
    ]
