# Generated by Django 5.1.3 on 2025-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0038_popup_popupdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geocoded_address',
            field=models.CharField(blank=True, help_text='Full geocoded address from Mapulus', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded longitude', max_digits=9, null=True),
        ),
    ]
