# Generated by Django 5.1.3 on 2025-11-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0039_user_geocoded_address_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=50)),
                ('last_name', models.CharField(help_text='Last name', max_length=50)),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], help_text='Email or Phone', max_length=10)),
                ('contact_value', models.CharField(help_text='Email address or phone number', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
