# Generated by Django 5.1.3 on 2026-01-05 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0040_discountregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTutoringClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Class title (e.g., 'French for Beginners')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed class description')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate_l1', 'Intermediate L1'), ('intermediate_l2', 'Intermediate L2'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('subject', models.CharField(default='French', help_text='Subject being taught', max_length=100)),
                ('start_date', models.DateField(help_text='When the class series begins')),
                ('end_date', models.DateField(help_text='When the class series ends')),
                ('max_students', models.PositiveIntegerField(default=20, help_text='Maximum number of students')),
                ('num_quizzes', models.PositiveIntegerField(default=0, help_text='Number of quizzes planned for this class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently accepting enrollments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Group Tutoring Classes',
                'ordering': ['-is_active', 'start_date', 'difficulty'],
            },
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='monthlyhours',
            name='payout_status',
        ),
        migrations.RemoveField(
            model_name='monthlyhours',
            name='transfer_id',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='confidence_attitude',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='homework_practice',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='looking_ahead',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='overall_progress',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='parent_support',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='work_habits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='geocoded_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='additional_comments',
            field=models.TextField(blank=True, default='', help_text='Any additional comments or observations'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='areas_for_improvement',
            field=models.TextField(default='', help_text='Areas where the student needs to improve'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='goals_for_next_month',
            field=models.TextField(default='', help_text='Goals and objectives for the upcoming month'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='homework_completion',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', help_text='How well the student completes homework assignments', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='participation_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text="Student's level of participation during sessions", max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='progress_summary',
            field=models.TextField(default='', help_text="Overall summary of the student's progress this month"),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('parent', 'Parents'), ('student', 'Students'), ('tutor', 'Tutors')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='strengths',
            field=models.TextField(default='', help_text="Student's strengths observed during tutoring sessions"),
        ),
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_diagnostic', 'Pending Diagnostic'), ('diagnostic_submitted', 'Diagnostic Submitted'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending_diagnostic', max_length=25)),
                ('requires_diagnostic', models.BooleanField(default=True, help_text='Whether student needs to take diagnostic')),
                ('diagnostic_score', models.FloatField(blank=True, help_text='Diagnostic test score (if applicable)', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about enrollment/diagnostic review')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments_as_parent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='playground.grouptutoringclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tutoring_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='One-time token for accessing the test', max_length=64, unique=True)),
                ('token_used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('token_expires_at', models.DateTimeField(help_text='When the token expires')),
                ('answers', models.JSONField(default=dict, help_text="Student's answers stored as JSON")),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reviews', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_submission', to='playground.groupenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='multiple_choice', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(blank=True, help_text='Correct answer or answer key', max_length=500)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points this question is worth')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_questions', to='playground.grouptutoringclass')),
            ],
            options={
                'ordering': ['tutoring_class', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of this session')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(help_text='Session end time')),
                ('title', models.CharField(blank=True, help_text='Session title/topic', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What will be covered in this session')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='playground.grouptutoringclass')),
            ],
            options={
                'ordering': ['session_date', 'start_time'],
                'unique_together': {('tutoring_class', 'session_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='File title/name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='group_tutoring_files/')),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='Week number (optional)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Is this from the current week?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_class_files', to=settings.AUTH_USER_MODEL)),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='playground.grouptutoringclass')),
            ],
            options={
                'ordering': ['-week_number', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(help_text='When the quiz is scheduled')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether students can currently take this quiz')),
                ('passing_score', models.FloatField(default=70.0, help_text='Passing score percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='playground.classsession')),
                ('tutoring_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='playground.grouptutoringclass')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('true_false', 'True/False')], default='multiple_choice', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(help_text='Correct answer', max_length=500)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='playground.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent'), ('cancelled_advance', 'Cancelled in Advance')], default='attended', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='playground.classsession')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='playground.groupenrollment')),
            ],
            options={
                'ordering': ['session', 'enrollment'],
                'unique_together': {('session', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='playground.groupenrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='playground.quiz')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('quiz', 'enrollment')},
            },
        ),
    ]
