# Generated by Django 5.1.3 on 2026-01-09 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0041_grouptutoringclass_remove_aichatsession_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptutoringclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Class duration in minutes'),
        ),
        migrations.AddField(
            model_name='grouptutoringclass',
            name='location',
            field=models.CharField(blank=True, help_text="Class location (e.g., 'Room 101', 'Online - Zoom')", max_length=200),
        ),
        migrations.AddField(
            model_name='grouptutoringclass',
            name='location_link',
            field=models.URLField(blank=True, help_text='Link for online classes (e.g., Zoom link)'),
        ),
        migrations.AddField(
            model_name='grouptutoringclass',
            name='schedule_days',
            field=models.JSONField(default=list, help_text="Days of the week when class meets (e.g., ['monday', 'wednesday'])"),
        ),
        migrations.AddField(
            model_name='grouptutoringclass',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Regular class meeting time', null=True),
        ),
        migrations.AddField(
            model_name='grouptutoringclass',
            name='tutors',
            field=models.ManyToManyField(help_text='Tutors assigned to teach this class', limit_choices_to={'roles': 'tutor'}, related_name='teaching_group_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
