# Generated by Django 5.1.3 on 2026-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0042_grouptutoringclass_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptutoringclass',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Background header image displayed on the class details page', null=True, upload_to='group_tutoring/headers/'),
        ),
    ]
