# Generated by Django 5.1.3 on 2026-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0044_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptutoringclass',
            name='schedule_times',
            field=models.JSONField(blank=True, default=dict, help_text="Per-day meeting times, e.g. {'monday': '15:00', 'wednesday': '16:30'}. Falls back to schedule_time for any scheduled day without an entry here."),
        ),
        migrations.AlterField(
            model_name='grouptutoringclass',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Regular class meeting time (legacy/default, used when a day has no entry in schedule_times)', null=True),
        ),
    ]
