# Generated by Django 5.1.3 on 2026-07-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0045_grouptutoringclass_schedule_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airequest',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='student',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='AiChatSession',
        ),
        migrations.DeleteModel(
            name='AiRequest',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
