# Generated by Django 5.1.3 on 2026-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0046_remove_airequest_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, help_text="Student's birth year (students only)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lives_with_parent',
            field=models.BooleanField(default=True, help_text='Whether this student lives with the parent who created their account (students only)'),
        ),
    ]
