# Generated by Django 5.1.3 on 2026-08-24 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0047_user_birth_year_user_lives_with_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(blank=True, choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Barrie', 'Barrie'), ('Belleville', 'Belleville'), ('Brampton', 'Brampton'), ('Brantford', 'Brantford'), ('Burlington', 'Burlington'), ('Cambridge', 'Cambridge'), ('Chatham-Kent', 'Chatham-Kent'), ('Clarington', 'Clarington'), ('Collingwood', 'Collingwood'), ('Cornwall', 'Cornwall'), ('Dryden', 'Dryden'), ('Georgina', 'Georgina'), ('Grimsby', 'Grimsby'), ('Guelph', 'Guelph'), ('Hamilton', 'Hamilton'), ('Huntsville', 'Huntsville'), ('Innisfil', 'Innisfil'), ('Kawartha Lakes', 'Kawartha Lakes'), ('Kenora', 'Kenora'), ('Kingston', 'Kingston'), ('Kitchener', 'Kitchener'), ('Leamington', 'Leamington'), ('London', 'London'), ('Markham', 'Markham'), ('Midland', 'Midland'), ('Milton', 'Milton'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('Niagara Falls', 'Niagara Falls'), ('Niagara-on-the-Lake', 'Niagara-on-the-Lake'), ('North Bay', 'North Bay'), ('Oakville', 'Oakville'), ('Orangeville', 'Orangeville'), ('Orillia', 'Orillia'), ('Oshawa', 'Oshawa'), ('Ottawa', 'Ottawa'), ('Peterborough', 'Peterborough'), ('Pickering', 'Pickering'), ('Quinte West', 'Quinte West'), ('Richmond Hill', 'Richmond Hill'), ('Sarnia', 'Sarnia'), ('St. Catharines', 'St. Catharines'), ('St. Thomas', 'St. Thomas'), ('Stratford', 'Stratford'), ('Sudbury', 'Sudbury'), ('Tecumseh', 'Tecumseh'), ('Thunder Bay', 'Thunder Bay'), ('Timmins', 'Timmins'), ('Toronto', 'Toronto'), ('Vaughan', 'Vaughan'), ('Wasaga Beach', 'Wasaga Beach'), ('Waterloo', 'Waterloo'), ('Welland', 'Welland'), ('Whitby', 'Whitby'), ('Windsor', 'Windsor'), ('Woodstock', 'Woodstock')], max_length=30)),
                ('school_type', models.CharField(blank=True, choices=[('elementary', 'Elementary'), ('high', 'High School'), ('other', 'Other/K-12')], max_length=15)),
                ('language_stream', models.CharField(blank=True, choices=[('english', 'English'), ('french', 'French'), ('french_immersion', 'French Immersion')], max_length=20)),
                ('board_name', models.CharField(blank=True, help_text='e.g. TDSB, Durham DSB, Conseil scolaire Viamonde', max_length=150)),
                ('gives_credits', models.BooleanField(default=False, help_text='If true, new students from this school are queued for admin credit-hour verification')),
                ('credit_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tutoring credit hours granted to a verified student from this school', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive schools are hidden from student-facing dropdowns but preserved for existing student references/history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hours',
            name='billing_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('credited', 'Credited')], default='normal', help_text="'credited' hours are paid by school credit, not the parent - excluded from weekly parent billing/invoices but still counted toward monthly tutor payouts. Never shown to tutors.", max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining school-credit tutoring hours for this student (students only)', max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='school_other_name',
            field=models.CharField(blank=True, help_text="Free-text school name when 'Other' is selected (students only)", max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('weekly_hours', 'Weekly Hours Summary'), ('monthly_hours', 'Monthly Hours Summary'), ('invoice', 'Invoice Notification'), ('invoice_reminder', 'Invoice Reminder'), ('verification', 'Email Verification'), ('welcome_tutor', 'Tutor Welcome'), ('welcome_parent', 'Parent Welcome'), ('tutor_reply', 'Tutor Reply'), ('new_request', 'New Request'), ('monthly_report', 'Monthly Report'), ('hour_dispute', 'Hour Dispute'), ('dispute_admin', 'Dispute Admin Notification'), ('referral_bonus', 'Referral Bonus'), ('referral_admin', 'Referral Admin Notification'), ('tutor_transfer', 'Tutor Transfer'), ('parent_registration', 'Parent Registration'), ('health_check', 'Health Check'), ('bulk_parent', 'Bulk Parent Email'), ('bulk_tutor', 'Bulk Tutor Email'), ('bulk_custom', 'Bulk Custom Email'), ('hours_reminder', 'Hours Reminder'), ('school_credit_admin', 'School Credit Admin Alert'), ('test', 'Test Email'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Student's school (students only)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='playground.school'),
        ),
        migrations.CreateModel(
            name='StudentSchoolCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_hours_snapshot', models.DecimalField(decimal_places=2, help_text="School's credit_hours value captured when this request was created or last corrected", max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(limit_choices_to={'roles': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_credit_requests_for_children', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_credits_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_requests', to='playground.school')),
                ('student', models.ForeignKey(limit_choices_to={'roles': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
