# Generated by Django 5.1.3 on 2026-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0050_alter_popup_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='audience',
            field=models.CharField(default='all', help_text='Comma-separated roles: e.g., "parent,tutor" or "all"', max_length=100),
        ),
    ]
