# Generated by Django 5.1.3 on 2026-08-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0051_alter_announcements_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringrequest',
            name='hidden_from_dashboard',
            field=models.BooleanField(default=False, help_text='Admin-hidden from the general tutor dashboard. The request itself is preserved, just not shown to tutors browsing for open requests.'),
        ),
    ]
