# Generated by Django 5.1.3 on 2026-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0052_tutoringrequest_hidden_from_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('weekly_hours', 'Weekly Hours Summary'), ('monthly_hours', 'Monthly Hours Summary'), ('invoice', 'Invoice Notification'), ('invoice_reminder', 'Invoice Reminder'), ('verification', 'Email Verification'), ('welcome_tutor', 'Tutor Welcome'), ('welcome_parent', 'Parent Welcome'), ('tutor_reply', 'Tutor Reply'), ('new_request', 'New Request'), ('monthly_report', 'Monthly Report'), ('hour_dispute', 'Hour Dispute'), ('dispute_admin', 'Dispute Admin Notification'), ('referral_bonus', 'Referral Bonus'), ('referral_admin', 'Referral Admin Notification'), ('tutor_transfer', 'Tutor Transfer'), ('parent_registration', 'Parent Registration'), ('tutor_registration', 'Tutor Registration'), ('health_check', 'Health Check'), ('bulk_parent', 'Bulk Parent Email'), ('bulk_tutor', 'Bulk Tutor Email'), ('bulk_custom', 'Bulk Custom Email'), ('hours_reminder', 'Hours Reminder'), ('school_credit_admin', 'School Credit Admin Alert'), ('test', 'Test Email'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
